### ISSUE TITLE
Security / data obfuscation

### ISSUE THREAD

**Issue by AlanBarber** [cloudcrate/BlazorStorage#23]
Any plans or thoughts about adding support for more secure storage of the key/value pairs? Obviously you shouldn't be storing anything ultra secure on browsers local storage but there are things that could be done to help limit abuse via dev tools.

I was thinking at a minimum maybe optionally being able to store the values base64 encoded or perhaps providing support for a full encryption module?

**Comment by LunicLynx** [comment]
Hi @AlanBarber,
is this something the javascript api supports? 
If so can you point me to the documentation?
Otherwise I'm afraid i think this is outside of the scope of this project. Don't get me wrong the idea is great! But i would implement it on top as extension methods, because the end result as i understand it currently would be storing an encrypted string.
We can certainly explore the idea of creating an additional package containing these convenience methods if that would be something you are interested in.

**Comment by alexanderjwoods** [comment]
@AlanBarber I know I am late the party, but I would suggest doing the obfuscation before calling `Storage.SetItem`

I.e.,
`var item = myItemToStore.ObfuscateValue();
Storage.SetItem(key, item);`

In this case `ObfuscateValue` would be an extension on whatever `myItemToStore`'s type is.
